### ISSUE TITLE
Выложить собранную cf

### ISSUE THREAD

**Issue by khorevaa** [LazarenkoA/1C_JIRA#1]
Или указать версию платформы на которыой надо собирать из исходников.

**Comment by LazarenkoA** [comment]
cf выложил. Однако хочу предупредить, что скорей всего под вашу JIRA придется дорабатывать т.к. данное решение разрабатывалась под JIRA с использованием сабтасков. Не знаю как ПО поведет себя при интеграции с JIRA без сабтасков

**Comment by khorevaa** [comment]
@LazarenkoA Я уже код видел и это понимаю!
